"""
Crypto Bot v4.4 — Core Models
Defines all shared data structures used across services.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional
from uuid import UUID, uuid4


# ═══════════════════════════════════════════════════════════════
# Enums
# ═══════════════════════════════════════════════════════════════

class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class Regime(str, Enum):
    TREND_HIGH_VOL = "trend_high_vol"
    TREND_LOW_VOL = "trend_low_vol"
    RANGE_HIGH_VOL = "range_high_vol"
    RANGE_LOW_VOL = "range_low_vol"
    BREAKOUT = "breakout"


class StrategyType(str, Enum):
    SWEEP = "sweep"
    BOUNCE = "bounce"
    BREAKOUT = "breakout"


class OrderType(str, Enum):
    LIMIT = "limit"
    MARKET = "market"
    STOP_MARKET = "stop_market"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    PENDING = "pending"
    FILLED = "filled"
    PARTIAL = "partial"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    WARNING = "warning"
    CRITICAL = "critical"


class ServiceMode(str, Enum):
    ONLINE = "online"
    OFFLINE = "offline"


# ═══════════════════════════════════════════════════════════════
# Core Data Models
# ═══════════════════════════════════════════════════════════════

@dataclass
class OHLCV:
    """OHLCV candle data."""
    timestamp: datetime
    pair: str
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "pair": self.pair,
            "timeframe": self.timeframe,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }


@dataclass
class Signal:
    """Trading signal generated by Strategy Engine."""
    pair: str
    direction: Direction
    entry_market: float
    entry_limit: float
    stop_loss: float
    tp1: float
    tp2: float
    strategy: StrategyType
    confidence: float
    regime: Regime
    factors: List[Dict]
    timestamp: datetime

    def __post_init__(self):
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")


@dataclass
class Trade:
    """Trade record."""
    trade_id: UUID = field(default_factory=uuid4)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    pair: str = ""
    direction: Direction = Direction.LONG
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    size: float = 0.0
    pnl: Optional[float] = None
    fees: float = 0.0
    strategy: StrategyType = StrategyType.SWEEP
    confidence: float = 0.0
    regime: Regime = Regime.TREND_HIGH_VOL
    signal: Optional[Signal] = None

    @property
    def is_closed(self) -> bool:
        return self.exit_price is not None


@dataclass
class Position:
    """Current open position."""
    pair: str
    direction: Direction
    entry_price: float
    size: float
    stop_loss: float
    tp1: float
    tp2: float
    strategy: StrategyType
    opened_at: datetime
    current_pnl: float = 0.0
    trade_id: UUID = field(default_factory=uuid4)


@dataclass
class ExecutionRecord:
    """Quality-of-execution log entry."""
    timestamp: datetime
    pair: str
    expected_price: float
    actual_price: float
    slippage: float
    latency: float  # milliseconds
    partial_fill: bool = False
    cancelled: bool = False

    @property
    def slippage_pct(self) -> float:
        if self.expected_price == 0:
            return 0.0
        return abs(self.slippage / self.expected_price)


# ═══════════════════════════════════════════════════════════════
# Feature Data
# ═══════════════════════════════════════════════════════════════

@dataclass
class Features:
    """Technical features for a given pair/timeframe."""
    timestamp: datetime
    pair: str
    timeframe: str
    adx_14: float = 0.0
    adx_21: float = 0.0
    atr_pct_14: float = 0.0
    atr_pct_21: float = 0.0
    atr_percentile: float = 0.0
    bb_upper: float = 0.0
    bb_lower: float = 0.0
    bb_middle: float = 0.0
    bb_width: float = 0.0
    volume_ma_20: float = 0.0
    volume_ma_50: float = 0.0
    volume_ratio: float = 0.0
    cvd: float = 0.0
    squeeze_active: bool = False
    liquidity_levels_above: List[float] = field(default_factory=list)
    liquidity_levels_below: List[float] = field(default_factory=list)
    wick_ratio: float = 0.0


@dataclass
class MarketRegime:
    """Detected market regime with strategy weights."""
    regime: Regime
    confidence: float
    adx: float
    atr_percentile: float
    strategy_weights: Dict[StrategyType, float] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)


# ═══════════════════════════════════════════════════════════════
# Risk & Portfolio
# ═══════════════════════════════════════════════════════════════

@dataclass
class RiskDecision:
    """Risk Engine decision on a signal."""
    approved: bool
    position_size: float
    stop_loss: float
    stop_multiplier: float
    rr_ratio: float
    reason: str = ""
    recovery_mode: bool = False


@dataclass
class PortfolioState:
    """Current portfolio state."""
    balance: float
    equity: float
    open_positions: int
    total_exposure: float
    daily_pnl: float
    weekly_pnl: float
    monthly_pnl: float
    daily_drawdown: float
    weekly_drawdown: float
    monthly_drawdown: float
    total_drawdown: float
    recovery_mode: bool
    timestamp: datetime = field(default_factory=datetime.utcnow)


# ═══════════════════════════════════════════════════════════════
# Events
# ═══════════════════════════════════════════════════════════════

class EventType(str, Enum):
    TRADE_OPENED = "trade_opened"
    TRADE_FILLED = "trade_filled"
    POSITION_CREATED = "position_created"
    STOP_MOVED = "stop_moved"
    POSITION_CLOSED = "position_closed"
    CONFIG_UPDATED = "config_updated"
    RECOVERY_ENTERED = "recovery_entered"
    RECOVERY_EXITED = "recovery_exited"
    HEALTH_CHANGED = "health_changed"


@dataclass
class Event:
    """Event sourcing event."""
    event_id: UUID = field(default_factory=uuid4)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    type: EventType = EventType.TRADE_OPENED
    data: dict = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════
# Config
# ═══════════════════════════════════════════════════════════════

@dataclass
class StrategyConfig:
    enabled: bool = True
    wick_ratio: float = 1.8
    volume_multiplier: float = 1.25
    tolerance: float = 0.0018
    min_rr: float = 2.0
    sl_atr_mult: float = 1.5
    tp_min: float = 0.02
    tp_max: float = 0.04


@dataclass
class RiskConfig:
    max_risk_per_trade: float = 0.015
    max_positions: int = 3
    max_correlation: float = 0.7
    max_exposure: float = 3.0
    stop_multipliers: Dict[str, float] = field(default_factory=lambda: {
        "ultra_quiet": 0.8,
        "quiet": 1.0,
        "normal": 1.2,
        "volatile": 1.5,
    })
    drawdown_limits: Dict[str, float] = field(default_factory=lambda: {
        "daily": 2.0,
        "weekly": 5.0,
        "monthly": 10.0,
        "max_total": 15.0,
    })
    recovery_threshold: float = 8.0
    recovery_exit_threshold: float = 5.0
    recovery_min_wins: int = 3


@dataclass
class LearningConfig:
    min_trades: int = 100
    min_windows: int = 3
    train_period: int = 6  # months
    test_period: int = 1    # month
    step: int = 1           # month
    score_weights: Dict[str, float] = field(default_factory=lambda: {
        "sharpe": 0.35,
        "profit_factor": 0.25,
        "drawdown": 0.20,
        "stability": 0.20,
    })


@dataclass
class ExecutionConfig:
    max_slippage: float = 0.0005
    limit_timeout: int = 60
    max_price_move: float = 0.002
    partial_fill_action: str = "adjust"


@dataclass
class RegimeConfig:
    adx_threshold: float = 25.0
    atr_percentiles: List[float] = field(default_factory=lambda: [20.0, 80.0])


@dataclass
class MonitoringConfig:
    data_latency_threshold: int = 500  # ms
    api_errors_threshold: int = 5       # per minute
    cpu_threshold: float = 80.0         # %
    memory_threshold: int = 2048        # MB


@dataclass
class SystemConfig:
    version: str = "4.4.1"
    created_at: datetime = field(default_factory=datetime.utcnow)
    hash: str = ""
    pairs: List[str] = field(default_factory=lambda: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT"])
    timeframes: List[str] = field(default_factory=lambda: ["15m", "1h", "4h", "1d"])
    lookback_days: int = 90
    service_mode: ServiceMode = ServiceMode.ONLINE
    strategy: Dict[StrategyType, StrategyConfig] = field(default_factory=dict)
    risk: RiskConfig = field(default_factory=RiskConfig)
    regime: RegimeConfig = field(default_factory=RegimeConfig)
    execution: ExecutionConfig = field(default_factory=ExecutionConfig)
    learning: LearningConfig = field(default_factory=LearningConfig)
    monitoring: MonitoringConfig = field(default_factory=MonitoringConfig)
